### ISSUE TITLE
TUCH regressor

### ISSUE THREAD

**Issue by leesky1c** [muelea/selfcontact#1]
Thanks for your great works. Will you public the 3D human pose regressor model(TUCH) in the future?

**Comment by muelea** [comment]
Yes, TUCH will be published as well. Either this or next week.
Best wishes,
Lea

**Comment by leesky1c** [comment]
Any progress?

**Comment by muelea** [comment]
I want to integrate the selfcontact repo in TUCH, which takes some time, but I am working on it.

**Comment by code-conquer** [comment]
Hello, when will the TUCH model be made public? It is so cool that I can't wait to try it.

**Comment by leesky1c** [comment]
@muelea Sorry to bother you again. How's it going?

**Comment by muelea** [comment]
Please visit https://github.com/muelea/tuch. I can't find time to integrate the self-contact package, so I just published as it is.
