### ISSUE TITLE
3DCP Dataset

### ISSUE THREAD

**Issue by GuyTevet** [muelea/selfcontact#3]
Thanks for your great work!
Looking at the released 3DCP dataset - Does it contain the reported *3DCP Mocap* dataset and how can I distinct *3DCP Mocap* from *3DCP Scan*?

Thanks:)

**Comment by GuyTevet** [comment]
Alternatively, will you be able to share the *Self-Contact Optimization* code?

**Comment by muelea** [comment]
The 3DCP pose and contact parameters are included in the MTP dataset on our website. The self-contact optimization code will be included into this repo.

**Comment by muelea** [comment]
The self-contact optimisation code is available now. You need to download the essentials again, they contain additional files and examples meshes. Then jump to 5) and try to run the example.

**Comment by GuyTevet** [comment]
Thanks! this is much appreciated :) Just note that you have 5) twice in the readme file.
