### ISSUE TITLE
Using SelfContact while training with AMASS dataset

### ISSUE THREAD

**Issue by GuyTevet** [muelea/selfcontact#6]
`SelfContact` supports SMPL and SMPLX models. Is it possible to use it while training with AMASS dataset (i.e. on top of SMPLH layer)?

Many thanks!

**Comment by muelea** [comment]
SMPL-H has the same topology as SMPL. That means that the segmentation and geodesic distances are also equal and that you can use the SMPL essentials for SMPL-H as well.

**Comment by GuyTevet** [comment]
Cool! Thanks:)
